<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.jl95terceira</groupId>
    <!--SWITCH:17-->
    <artifactId>batteries</artifactId>
    <!--END-->
    <!--SWITCH:8-->
<!--OFF:    <artifactId>batteries-8</artifactId>-->
    <!--END-->
    <description>Batteries</description>
    <version>0.1.0</version>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.json</artifactId>
            <version>1.1.4</version>
        </dependency>
        <!--SWITCH:8-->
<!--OFF:        <dependency>-->
<!--OFF:            <groupId>org.apache.commons</groupId>-->
<!--OFF:            <artifactId>commons-lang3</artifactId>-->
<!--OFF:            <version>3.14.0</version>-->
<!--OFF:        </dependency>-->
        <!--END-->
    </dependencies>
    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
              <groupId>org.sonatype.central</groupId>
              <artifactId>central-publishing-maven-plugin</artifactId>
              <version>0.6.0</version>
              <extensions>true</extensions>
              <configuration>
                <publishingServerId>central</publishingServerId>
              </configuration>
            </plugin>
        </plugins>
    </build>
    <url></url>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!--SWITCH:17-->
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <!--END-->
        <!--SWITCH:8-->
<!--OFF:        <maven.compiler.source>8</maven.compiler.source>-->
<!--OFF:        <maven.compiler.target>8</maven.compiler.target>-->
        <!--END-->
    </properties>
</project>